- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      become: yes
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      #register: initialize

      #- debug: msg="{{ initialize.stdout }}"
    - name: Wait init to complete and generate admin.conf
      wait_for:
        path: /etc/kubernetes/admin.conf


    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
    #- name: Wait init to complete and generate admin.conf
    #  wait_for:
    #    path: /etc/kubernetes/admin.conf

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt

      args:
        chdir: $HOME
        creates: pod_network_setup.txt
