#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql
#spec:
#  ports:
#  - port: 3306
#  selector:
#    app: mysql
#  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: db-sensyne
  name: db-sensyne
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db-sensyne
    spec:
      containers:
      - args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        env:
        - name: MYSQL_DATABASE
          value: sensyne
        - name: MYSQL_PASSWORD
          value: sensyne
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_USER
          value: sensyne
        image: mysql:5.7.21
        name: db-sensyne
        ports: 
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - name: mysql-persistent-storage2
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage2
        persistentVolumeClaim:
          claimName: mysql-pv-claim2
status: {}

